[manifest]
version = "1.0.0"
dump_lua = true
priority = 9999999999

[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = "if location == 'front' or self.config.type == 'deck' then"
position = "before"
payload = "self.cards = self.cards or {}"
match_indent = true

[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = "if (self == G.hand or self == G.deck or self == G.discard or self == G.play) and G.view_deck and G.view_deck[1] and G.view_deck[1].cards then return end"
position = "after"
payload = "self.children = self.children or {}"
match_indent = true